import modeler.api

stream = modeler.script.stream()
node1 = stream.findByID('id7SFVNS6XWT2')
fields = ['REV_EMPLOI_REL_1_2_T', 'AUTRE_REV_REL_1_2_T', 'PREST_VIAGERE_RPA_RPNA_REL_2_2_T', 'PREST_REER_FERR_RPDB_REL_2_2_T', 'AUTRE_PAIEMENT_REL_2_2_T', 'REMB_PRIM_CONJ_REER_REL_2_2_T', 'MT_AVANT_DECES_REER_REL_2_2_T', 'REMB_VERS_NON_DEDUI_REL_2_2_T', 'MT_RECU_REVOC_REER_REL_2_2_T', 'AUTRE_REV_REER_FERR_REL_2_2_T', 'REV_APRE_DECES_REER_REL_2_2_T', 'MT_IMPOSABLE_DIVIDENDE_REL_3_2_T', 'INTERET_SOURCE_CAN_REL_3_2_T', 'AUTRE_REV_SOURCE_CAN_REL_3_2_T', 'REVENU_BRUT_ETRANGER_REL_3_2_T', 'REDEVANCE_SOURCE_CAN_REL_3_2_T', 'DIVIDENDE_GAIN_CAPITAL_REL_3_2_T', 'REVENU_ACCUMULE_RENTE_REL_3_2_T', 'PREST_INDEM_MES_REL_5_2_T', 'PREST_INDEM_CSST_REL_5_2_T', 'PREST_INDEM_SAAQ_REL_5_2_T', 'AVANCE_TVQ_MES_REL_5_2_T', 'AUTRE_AIDE_FINANC_MES_R5_2_T', 'AUTRE_AIDE_FINANC_CSST_R5_2_T', 'AUTRE_AIDE_FINANC_SAAQ_REL_5_2_T' ,'AUTRE_REVENU_REL_5_2_T', 'REMBOURS_PREST_TOTAL_MES_R5_2_T']

node1.setPropertyValue("fields", fields)
node1.setPropertyValue("replace_mode", "Null")
